### ISSUE TITLE
Support Host Volume Binding

### ISSUE THREAD

**Issue by tiritibambix** [dotnetfactory/fluid-calendar#23]
Hi,

I find the project very cool and was curious to test it while waiting for CalDAV calendar management and an official image.

So I've been setting up Fluid Calendar with Docker Compose and ran into a small issue. I prefer managing my application data directly on my host machine for easier backups and data manipulation. However, when I tried to bind volumes to the host, the application couldn't start because it couldn't find the `entrypoint.sh` file.

Using Docker volumes solved the issue, but it means I can't manage the data as easily as I'd like. I think it would be great if the project could support binding volumes to the host machine. This way, users like me could manage data more effectively while still using Docker.

Here's a quick example of how the `docker-compose.yml` could look:

```yaml
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - /srv/Files/FluidCalendar:/app
      - /app/node_modules
      - /srv/Files/FluidCalendar/next_cache:/app/.next
      - /srv/Files/FluidCalendar/turbo_cache:/app/.turbo
      - /srv/Files/FluidCalendar/build_cache:/app/.cache
    environment:
      - DATABASE_URL=postgresql://fluid:fluid@db:5432/fluid_calendar
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=fluid
      - POSTGRES_PASSWORD=fluid
      - POSTGRES_DB=fluid_calendar
    ports:
      - "5432:5432"
    volumes:
      - /srv/Files/FluidCalendar/postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluid -d fluid_calendar"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
```

I think this change would make the project more flexible and user-friendly. Thanks for considering this!
What I've seen so far is very excinting!

**Comment by Medformatik** [comment]
I have set up Fluid Calendar with Docker host volume bindings. The docker-compose.yml file is located in the `/docker/fluid-calendar/` folder and I have cloned the repository in `/docker/fluid-calendar/live/`. This is necessary for building the image (important: the path for `build` is adjusted) and for the `entrypoint.sh` file.

```yaml
services:
  app:
    build:
      context: ./live
      target: development
    ports:
      - "3000:3000"
    volumes:
      - /docker/fluid-calendar/live:/app
      - /docker/fluid-calendar/next_cache:/app/.next
      - /docker/fluid-calendar/turbo_cache:/app/.turbo
      - /docker/fluid-calendar/build_cache:/app/.cache
    environment:
      - DATABASE_URL=postgresql://fluid:fluid@db:5432/fluid_calendar
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=fluid
      - POSTGRES_PASSWORD=fluid
      - POSTGRES_DB=fluid_calendar
    ports:
      - "5432:5432"
    volumes:
      - /docker/fluid-calendar/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fluid -d fluid_calendar" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
```

**Comment by Snuupy** [comment]
> and for the `entrypoint.sh` file

Do you mean that you made changes to `entrypoint.sh`, or that changing the build context line in the compose file is sufficient? I'm not able to get it working with just changing the build context line in the compose yml. @Medformatik

**Comment by Medformatik** [comment]
I didn't change anything in `entrypoint.sh`, just in the `docker-compose.yml`.

**Comment by Snuupy** [comment]
Looks like I am running into this issue https://github.com/dotnetfactory/fluid-calendar/issues/59

**Comment by eibrahim** [comment]
I am a bit confused, do you think you can create a PR of your suggestion/fix?  I am not sure what the problem is or how/what to fix?  

thanks.

**Comment by Medformatik** [comment]
The problem with host volume binding instead of docker volumes is that the code cannot be in the same directory as the other data directories (as far as I understand it). Therefore I have cloned the repository into the subdirectory `live/` and therefore specify `build: context: ./live`. This also results in these host volume bindings:

```
volumes:
  - /docker/fluid-calendar/live:/app
  - /docker/fluid-calendar/next_cache:/app/.next
  - /docker/fluid-calendar/turbo_cache:/app/.turbo
  - /docker/fluid-calendar/build_cache:/app/.cache
```

I also described this in my post above. I could of course create a PR, but I don't think that would be useful. In the long term, it would be better if ready-built images were available on Docker Hub or here on GitHub, so that you specify an image in `docker-compose.yml` and not a build target to build yourself.

**Comment by eibrahim** [comment]
I created ready built images last night.  Get latest and see readme.

If that addresses your issues let me know

**Comment by tiritibambix** [comment]
> I created ready built images last night. Get latest and see readme.
> 
> If that addresses your issues let me know

Thank you for providing an image.

### **Context:**  
- I'm using **Portainer** to deploy the stack.  
- My ports **3000 and 5432 are already in use**, so I had to change them.  
- My installation is located in `/srv/Files/Fluidcalendar/`.  
- I adapted the `docker-compose.yml` from the project ([[original file here](https://github.com/dotnetfactory/fluid-calendar/blob/main/docker-compose.yml)](https://github.com/dotnetfactory/fluid-calendar/blob/main/docker-compose.yml)) to the following:  

```yaml
services:
  app:
    image: eibrahim/fluid-calendar:latest
    ports:
      - "3087:3000"  # Changed from 3000
    env_file:
      - stack.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=fluid
      - POSTGRES_PASSWORD=fluid
      - POSTGRES_DB=fluid_calendar
    ports:
      - "5433:5432"  # Changed from 5432
    volumes:
      - /srv/Files/Fluidcalendar/postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluid -d fluid_calendar"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
```

### **My `.env` file (loaded via Portainer as `stack.env`)**  

```ini
# Database Configuration
DATABASE_URL="postgresql://fluid:fluid@db:5433/fluid_calendar"

# NextAuth Configuration
# Use domain in production, localhost for development
NEXTAUTH_URL="http://localhost:3087"
NEXT_PUBLIC_APP_URL="http://localhost:3087"
NEXTAUTH_SECRET="32charcomplicatedkey"
NEXT_PUBLIC_SITE_URL="http://localhost:3087"

NEXT_PUBLIC_ENABLE_SAAS_FEATURES=false

RESEND_API_KEY=
RESEND_FROM_EMAIL=
```

### **What Works:**  
- The **PostgreSQL database starts fine**. I can manually connect to it:  
  ```sh
  docker exec -it fluidcalendar-db-1 psql -U fluid -d fluid_calendar
  ```
- The tables are created, and everything looks fine inside the database.  

### **The Problem:**  
- The app container logs **keep saying "Waiting for database to be ready..."**  
- The app doesn't seem to connect to PostgreSQL, even though the database is running and accessible manually.  

### **What I’ve Tried:**  
- Checking the `DATABASE_URL` inside the app container:  
  ```sh
  docker exec -it fluidcalendar-app-1 sh -c 'echo $DATABASE_URL'
  ```
  → It looks correct (`postgresql://fluid:fluid@db:5433/fluid_calendar`).  
- Installing `postgresql-client` inside the app container and testing the connection:  
  ```sh
  apk add --no-cache postgresql-client
  psql "$DATABASE_URL"
  ```
  → **Returns "Connection refused"**.  
- Checking PostgreSQL logs:  
  ```sh
  docker logs fluidcalendar-db-1
  ```
  → No errors, database is ready and listening.  

### **Questions:**  
1. **Is this `docker-compose.yml` correct for running Fluid Calendar on Portainer?**  
2. Does the app require any **manual database migrations** before running? (`npx prisma migrate deploy` ?)  
3. Does `depends_on: service_healthy` correctly handle waiting for PostgreSQL, or should I add a wait-for-db script?  
4. Any idea why the app is not able to connect even though PostgreSQL is accessible?  

Would appreciate any help! Thanks. 🙏
